### PR TITLE
add orderby and set examples

### PR DESCRIPTION
**Pull request by benkoshy**
hi all
here are some order by tests to get you started. I will add more to it when i get the opportunity.

rgds

Ben

### CODE REVIEW

**Comment by zbma** [comment]
@BKSpurgeon Great! I've two requests though

1) Why did you remove `Answers/Partition.txt`? Seems fine to me. Can you recover it?
2) Rename `TestData.OrderByWords1` to `TestData.OrderByWordsExtended`

**Comment by benkoshy** [comment]
@walkhard greetings,

let me address  your questions in turn:

1. i thought about what you said re: answers - you are right they are simple answers so just got rid of them entirely. i'm sure i can recover via git.

2. no problem will rename.

rgds

Ben

**Comment by zbma** [comment]
@BKSpurgeon Either we include all answers or none, please recover it and I'll accept.

Thanks

**Comment by benkoshy** [comment]
hi @walkhard have recovered some missing answers, have added partitions and set operators also. have added a few tricky problems in there as well to challenge students. 

Perhaps I will create a separate class which requires students to combine different methods together to solve a particular problem.

rgds

Ben

**Comment by zbma** [comment]
@BKSpurgeon There are couple of things which I want you to fix.

1) `OrderBy-SelectedAnswers` do not fit current answers format, can you please make it look like other answer files?
2) Each line in `PartitionAnswers` starts with `-`, can you deal with it?
3) There is a typo in `SetAnsers`, it should be `SetAnswers`.
4) You mentioned that you want to create a separate class which uses combined methods to solve a problem. I like that idea.
5) `SetAnswers` one exercise is more complicated (more than one line of code to solve it). Maybe it could be our first excercise for 4)?
6) There are some extra whitespaces/indentation irregularities in `SetOperations` (possibly in other files too). Would you tidy it up? I can recommend a plugin for VS called [CodeMaid](http://www.codemaid.net/) which will automatically do it for you among other nice things.
7) Make sure comments are consistient (all above code, not in the same line).  Also, I think that it is obvious and we can acually remove those comments.:
`// please edit/complete so that the test passes`

 It looks like you're doing it in a hurry, no need to rush Ben. Thanks for your efforts!

**Comment by benkoshy** [comment]
@walkhard ok chrs for the posts - keeps me honest :P - i didn't realise those issues - I will update all those when i get the chance. pls bear with me time-wise, but will get to it
rgds
Ben

**Pull request merged**
