### PR TITLE
add partion linq examples

### PR DESCRIPTION
**Pull request by benkoshy**
Hi all

I've added some partioning examples. I plan to do the others over the course of the next month.

Enjoy it!

with kind regards

Ben

### CODE REVIEW

**Comment by zbma** [comment]
Great! Firstly, I think, we should discuss couple of things.

1. I think that *Partition* would be a better name than *Partion*
2. I've already said why I don't want to provide answers in #1 The idea with regions is interesting, though I think it's still too easy to look it up there (even by accident). I'd remove answers for now, at least from main repo, after all it's all rather basic stuff. Alternative idea is to create another repo with solutions. What do you think?
3. I like the idea with test data being included inside tests, visiblity is better, but it creates two tiny drawbacks. How do you propose to solve these?
    1. Not all tests inlude test data (in comments) and for some of tests (e.g. `TestData.People`) it'd be much harder and too verbose to include it in each test. For numeric tests however maybe it would be better to just use `int[] numbers = ...;` instead of `TestData.Numbers` to increase visibility. We should stick to arrange-act-assert scheme.
    2. If test data becomes changed we'll need to replace it in every comment, which is easy to forget. Keep in mind that we'll may or may not expand test data for new tests.

If you're going to work on something then please create ticket first, so nobody else will work on the same thing as you do.

I appreciate it and I'm willing to merge your work as soon as those things will be resolved.

Thanks :)

**Comment by benkoshy** [comment]
@walkhard chrs

1. Partition sounds good - I have now renamed the class.
2. answers - i am in complete agreement with you: students gain nothing by reading the answers. practice is what forces the learning. then i thought about it: i am acutely aware that the users are demanding answers - not for checking in and of itself but for pedagogical purposes: to see how others went about solving the problem. Personally I think that whoever downloads this repo is going to give the problems a good fight before caving in to see the solution - if at all they can't work it out. In other words, if a student still can't work out a problem after giving it a good attempt, how will he or she then learn? it's a double edged sword. give em what they want is what i say. anyways: shall i remove the answers? 
3. (1) yeah in agreement. the comments are a hack solution. in any case the students just wants to see the structure of the class, rather than the specifics, otherwise it's a pain flicking back and forth. (2) agreement again: it's all a trade off between ease of use for the student vs maintainability. i thought go for the former. it's a small repo so find and replace can be easily used.

**summary**

- i'll make the changes requested for 3 and 1.
- will create a ticket.
- please reconfirm whether you want the answers removed? i'll then resubmit.

rgds

Ben

**Comment by zbma** [comment]
@BKSpurgeon About those answers, you've got a point there. I'm still not 100% convinced, but there may be someone who needs a bit of help with exercises, besides @khtan already requested to include answers. So it may be a good idea to include it. Lets remove answers from code, so it won't be as easily accessible as it is now (and maybe a little bit less tempting ;), but lets create a text file (or a new class) which will contain all the answers, something simple as test name and solution.

I'd accept something like that.

**Comment by benkoshy** [comment]
@walkhard made the requested changes.  I think you should automatically see the changes without me making another pull request. I'll add more tests - over time. rgds, Ben

**Pull request merged**
